name: auto-changelog for walt.id XYZ Kit

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  auto-changelog:
    name: "Auto Changelog"
    runs-on: "ubuntu-latest"
    steps:
    - name: Changelog
      uses: ardalanamini/auto-changelog@v3
      id: changelog
      with:
        github-token: ${{ github.token }}
        commit-types: |
          breaking: Breaking Changes
          feat: New Features
          fix: Bug Fixes
          revert: Reverts
          perf: Performance Improvements
          refactor: Refactors
          deps: Dependencies
          docs: Documentation Changes
          style: Code Style Changes
          build: Build System
          ci: Continuous Integration
          test: Tests
          chore: Chores
          other: Other Changes
        default-commit-type: Other Changes
        release-name: v1.0.0
        mention-authors: true
        mention-new-contributors: true
        include-compare: true
        semver: true
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          ${{ steps.changelog.outputs.changelog }}
        prerelease: ${{ steps.changelog.outputs.prerelease }}