name: Build on every push

on: [push, pull_request]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Calculate release version
        run: |
          echo "release_version=1.$(date +'%g%m%d%H%M').$(echo ${{ github.ref_name }} | tr / -)" >> $GITHUB_ENV
      - name: Set version
        run: |
          sed -i "s/1.SNAPSHOT/${{ env.release_version }}/g" build.gradle.kts src/main/kotlin/id/walt/Values.kt
      - run: |
          git tag ${{ env.release_version }}
          git push --tags
