name: CI/CD Workflow for walt.id XYZ Kit

on:
  push:
    branches:
      - 2-trigger-release-on-pr-mergeclose-pr3
  pull_request:
    branches:
      - main

jobs:
  release:
    name: "Verification"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          release-name: v1.0.0
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}