name: CI/CD Workflow for walt.id XYZ Kit

on:
  push:
    branches:
      - 2-trigger-release-on-pr-mergeclose
  pull_request:
    branches:
      - main

jobs:
  verify-wrapper:
    name: "Verification"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  gradle:
    needs: verify-wrapper
    name: "Build"
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt-hotspot'
        java-version: '16'
    - name: Running gradle build
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        arguments: build --no-daemon --info
    - name: Changelog
      uses: ardalanamini/auto-changelog@v3
      id: changelog
      with:
        github-token: ${{ github.token }}
        commit-types: |
          breaking: Breaking Changes
          feat: New Features
          fix: Bug Fixes
          revert: Reverts
          perf: Performance Improvements
          refactor: Refactors
          deps: Dependencies
          docs: Documentation Changes
          style: Code Style Changes
          build: Build System
          ci: Continuous Integration
          test: Tests
          chore: Chores
          other: Other Changes
        default-commit-type: Other Changes
        release-name: v1.0.0
        mention-authors: true
        mention-new-contributors: true
        include-compare: true
        semver: true
