name: Docker Compose Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  WALLET_BACKEND_PORT: 3000
  ISSUER_API_PORT: 3001
  VERIFIER_API_PORT: 3002
  WALLET_FRONTEND_PORT: 3003
  WEB_PORTAL_PORT: 3004
  VC_REPO_PORT: 3005

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.8
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker Images
        run: docker-compose pull
      - name: Run Docker Compose
        run: docker-compose up --abort-on-container-exit
