name: environment-variables for walt.id XYZ Kit

on:
  push:
    branches:
      - feat-update-filexyz

jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables
        run: env
