name: load testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: src/main/test/test.js

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: summary.json


