name: load testing
on:
  push:
    branches:
      - 1-integrate-k6-with-github-actions-in-project-waltid-xyz-kit
  pull_request:
    branches:
      - 1-integrate-k6-with-github-actions-in-project-waltid-xyz-kit

jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: src/main/test/test.js
      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: result.html
      - name: Send mail
        if:  ${{ failure() }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: ahmed@walt.id
          from: walt test
