name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release version
        run: |
          echo "release_version=1.$(date +'%g%m%d%k')" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.release_version }}" 

      - name: Call a Bash Script
        run:  ./xyzkit set-release-version
