name: tag for walt.id XYZ Kit

on:
  push:
    branches:
      - 2-trigger-release-on-pr-mergeclose-pr3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git tag v3.4.5
          git push --tags