name: TAG

on:
  push:
    branches:
      - xxx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate release version
        run: |
          echo "release_version=1.$(date +'%g%m%d')" >> $GITHUB_ENV
      - name: Set version
        run: |
          sed -i "s/1.SNAPSHOT/${{ env.release_version }}/g" build.gradle.kts src/main/kotlin/id/walt/Values.kt
      - run: |
          git tag ${{ env.release_version }}
          git push --tags