name: tag for walt.id XYZ Kit

on:
  push:
    branches:
      - 2-trigger-release-on-pr-mergeclose-pr3

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      -
      - run: git tag v3.4.5 && git push --tags