name: TAG

on:
  push:
    branches:
      - 2-trigger-release-on-pr-mergeclose-pr3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git tag $(date + "%s")
          git push --tags