name: Deploy manually to test environment

on:
  workflow_dispatch:

jobs:
  build:
    name: "Deploy to test environment"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     push: true
      #     tags: waltid/xyzkit:latest, waltid/xyzkit:${{ github.ref }}
      - name: Prepare CD
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" k8s/deployment-dev.yaml > k8s/deployment_mod.yaml
      # - name: Continuous deployment
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: apply -n portals -f k8s/deployment_mod.yaml
